

function classColorsCodes()
{
    var out = [

        {className: 'label_0', IdentifiedType: 'label_0', color: '#FFFFFF'},
        {className: 'label_1', IdentifiedType: 'label_1', color: '#3DCCFF'},
        {className: 'label_2', IdentifiedType: 'label_2', color: '#FFFFFF'},
        {className: 'label_3', IdentifiedType: 'label_3', color: '#1FADEB'},
        {className: 'label_4', IdentifiedType: 'label_4', color: '#FFFFFF'},
        {className: 'label_5', IdentifiedType: 'label_5', color: '#3D855A'},
        {className: 'label_6', IdentifiedType: 'label_6', color: '#FFFFFF'},
        {className: 'label_7', IdentifiedType: 'label_7', color: '#FFFFFF'},
        {className: 'label_8', IdentifiedType: 'label_8', color: '#FFFFFF'},
        {className: 'label_9', IdentifiedType: 'label_9', color: '#FFFFFF'},
        {className: 'label_10', IdentifiedType: 'label_10', color: '#FFFFFF'},
        {className: 'label_11', IdentifiedType: 'label_11', color: '#FFFFFF'},
        {className: 'label_12', IdentifiedType: 'label_12', color: '#7757FA'},
        {className: 'label_13', IdentifiedType: 'label_13', color: '#FFFFFF'},
        {className: 'label_14', IdentifiedType: 'label_14', color: '#FFFFFF'},
        {className: 'label_15', IdentifiedType: 'label_15', color: '#FFFFFF'},
        {className: 'label_16', IdentifiedType: 'label_16', color: '#5938DB'},
        {className: 'label_17', IdentifiedType: 'label_17', color: '#FF0000'},
        {className: 'label_18', IdentifiedType: 'label_18', color: '#FFFFFF'},
        {className: 'label_19', IdentifiedType: 'label_19', color: '#FFFFFF'},
        {className: 'label_20', IdentifiedType: 'label_20', color: '#996E00'},
        {className: 'label_21', IdentifiedType: 'label_21', color: '#FFFFFF'},
        {className: 'label_22', IdentifiedType: 'label_22', color: '#FFFFFF'},
        {className: 'label_23', IdentifiedType: 'label_23', color: '#FFFFFF'},
        {className: 'label_24', IdentifiedType: 'label_24', color: '#FFFFFF'},
        {className: 'label_25', IdentifiedType: 'label_25', color: '#FF00E6'},
        {className: 'label_26', IdentifiedType: 'label_26', color: '#FFFFFF'},
        {className: 'label_27', IdentifiedType: 'label_27', color: '#FFFFFF'},
        {className: 'label_28', IdentifiedType: 'label_28', color: '#FFFFFF'},
        {className: 'label_29', IdentifiedType: 'label_29', color: '#FFFFFF'},
        {className: 'label_30', IdentifiedType: 'label_30', color: '#BDA800'},
        {className: 'label_31', IdentifiedType: 'label_31', color: '#FFFFFF'},
        {className: 'label_32', IdentifiedType: 'label_32', color: '#FFFFFF'},
        {className: 'label_33', IdentifiedType: 'label_33', color: '#FFFFFF'},
        {className: 'label_34', IdentifiedType: 'label_34', color: '#FFFFFF'},
        {className: 'label_35', IdentifiedType: 'label_35', color: '#FFFFFF'},
        {className: 'label_36', IdentifiedType: 'label_36', color: '#FFFFFF'},
        {className: 'label_37', IdentifiedType: 'label_37', color: '#FFFFFF'},
        {className: 'label_38', IdentifiedType: 'label_38', color: '#FFFFFF'},
        {className: 'label_39', IdentifiedType: 'label_39', color: '#FAE52E'},
        {className: 'label_40', IdentifiedType: 'label_40', color: '#DBC70F'},
        {className: 'label_41', IdentifiedType: 'label_41', color: '#994D91'},
        {className: 'label_42', IdentifiedType: 'label_42', color: '#FFFFFF'},
        {className: 'label_43', IdentifiedType: 'label_43', color: '#008FCC'},
        {className: 'label_44', IdentifiedType: 'label_44', color: '#ff8911'},
        {className: 'label_45', IdentifiedType: 'label_45', color: '#FFFFFF'},
        {className: 'label_46', IdentifiedType: 'label_46', color: '#FFFFFF'},
        {className: 'label_47', IdentifiedType: 'label_47', color: '#0070AD'},
        {className: 'label_48', IdentifiedType: 'label_48', color: '#FFFFFF'},
        {className: 'label_49', IdentifiedType: 'label_49', color: '#FFFFFF'},
        {className: 'label_50', IdentifiedType: 'label_50', color: '#00FF00'},
        {className: 'label_51', IdentifiedType: 'label_51', color: '#73E500'},
        {className: 'label_52', IdentifiedType: 'label_52', color: '#FFFFFF'},
        {className: 'label_53', IdentifiedType: 'label_53', color: '#1F663B'},
        {className: 'label_54', IdentifiedType: 'label_54', color: '#a66c77'},
        {className: 'label_55', IdentifiedType: 'label_55', color: '#FFFFFF'},
        {className: 'label_56', IdentifiedType: 'label_56', color: '#91ffc5'},
        {className: 'label_57', IdentifiedType: 'label_57', color: '#FFFFFF'},
        {className: 'label_58', IdentifiedType: 'label_58', color: '#1a4cff'},
        {className: 'label_59', IdentifiedType: 'label_59', color: '#ff94e9'},
        {className: 'label_60', IdentifiedType: 'label_60', color: '#aca5ff'},
        {className: 'label_61', IdentifiedType: 'label_61', color: '#FFFFFF'},
        {className: 'label_62', IdentifiedType: 'label_62', color: '#FFFFFF'},
        {className: 'label_63', IdentifiedType: 'label_63', color: '#FFFFFF'},
        {className: 'label_64', IdentifiedType: 'label_64', color: '#FFFFFF'},
        {className: 'label_65', IdentifiedType: 'label_65', color: '#FFFFFF'},
        {className: 'label_66', IdentifiedType: 'label_66', color: '#FFFFFF'},
        {className: 'label_67', IdentifiedType: 'label_67', color: '#FFFFFF'},
        {className: 'label_68', IdentifiedType: 'label_68', color: '#b1fff8'},
        {className: 'label_69', IdentifiedType: 'label_69', color: '#FFFFFF'},
        {className: 'label_70', IdentifiedType: 'label_70', color: '#FFFFFF'},
        {className: 'label_71', IdentifiedType: 'label_51', color: '#FFFFFF'},
        {className: 'label_72', IdentifiedType: 'label_52', color: '#FFFFFF'},
        {className: 'label_73', IdentifiedType: 'label_53', color: '#ffc8bf'},
        {className: 'label_74', IdentifiedType: 'label_54', color: '#FFFFFF'},
        {className: 'label_75', IdentifiedType: 'label_55', color: '#FFFFFF'},
        {className: 'label_76', IdentifiedType: 'label_56', color: '#FFFFFF'},
        {className: 'label_77', IdentifiedType: 'label_57', color: '#FFFFFF'},
        {className: 'label_78', IdentifiedType: 'label_58', color: '#FFFFFF'},
        {className: 'label_79', IdentifiedType: 'label_59', color: '#FFFFFF'},
        {className: 'label_80', IdentifiedType: 'label_60', color: '#FFFFFF'},
        {className: 'label_81', IdentifiedType: 'label_51', color: '#FFFFFF'},
        {className: 'label_82', IdentifiedType: 'label_52', color: '#FFFFFF'},
        {className: 'label_83', IdentifiedType: 'label_53', color: '#FFFFFF'},
        {className: 'label_84', IdentifiedType: 'label_54', color: '#FFFFFF'},
        {className: 'label_85', IdentifiedType: 'label_55', color: '#FFFFFF'},
        {className: 'label_86', IdentifiedType: 'label_56', color: '#FFFFFF'},
        {className: 'label_87', IdentifiedType: 'label_57', color: '#FFFFFF'},
        {className: 'label_88', IdentifiedType: 'label_58', color: '#FFFFFF'},
        {className: 'label_89', IdentifiedType: 'label_59', color: '#FFFFFF'},
        {className: 'label_90', IdentifiedType: 'label_60', color: '#FFFFFF'},
        {className: 'label_91', IdentifiedType: 'label_61', color: '#FFFFFF'},
        {className: 'label_92', IdentifiedType: 'label_62', color: '#FFFFFF'},
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},


        // I added this
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#C0C0C0'},


    ];

    return out
}